packageExtensions:
  "@vxna/mini-html-webpack-template@*":
    dependencies:
      mini-html-webpack-plugin: ^0.2.3
  react-docgen-annotation-resolver@*:
    dependencies:
      react-docgen: ^4.1.1
  react-styleguidist@*:
    peerDependencies:
      webpack: ^5.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-rc.js
