name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  support:
    if: github.event_name == 'pull_request' && !contains(github.event.head_commit.message, '[skip-ci]')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [10, 12, 13]
        exclude:
          - os: ubuntu-latest
            node: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn build

  check-cache:
    if: github.actor != 'emortlock'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install --check-cache

  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn
      - run: yarn build
      - run: yarn ci:test
      - run: yarn docs

  publish:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip-ci]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn
      - run: yarn ci:test

      - name: Run release action
        uses: ./.github/actions/release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - run: yarn ci:docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
