name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build
    - run: npm run docs
    - name: upload workspace
      uses: actions/upload-artifact@v1
      with:
        name: workspace
        path: ./

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: download workspace
      uses: actions/upload-artifact@v1
      with:
        name: workspace
    - run: npm run lint
    - run: npm test

  publish:
    needs: [build, test]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: download workspace
      uses: actions/upload-artifact@v1
      with:
        name: workspace
    - name: release
      uses: ./.github/actions/release 
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
        NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    - run: npx gh-pages -d "docs" -b "gh-pages" -r "https://${ACTIONS_DEPLOY_KEY}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}" -x
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
